### ISSUE TITLE
Unable to revive connection

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify-elasticsearch#14]
Hello everyone! I'm trying to use this plugin into my application. I have a local elasticsearch running on my server, but can't connect.

```
➜  nomikos git:(audit) ✗ curl localhost:9200
{
  "name" : "RAWsTdY",
  "cluster_name" : "elasticsearch_lgertel",
  "cluster_uuid" : "mkTSJnzjTYqzEIiU4aCPyw",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

And, after registering the plugin with the options: 
```
fastify.register(require('fastify-elasticsearch'), {
    host: 'localhost',
    port: 9200
  })
```
I'm getting:
```
> fastify start -l info app.js -P --inspect

Elasticsearch ERROR: 2018-06-27T12:47:49Z
  Error: Request error, retrying
  HEAD http://localhost/ => connect ECONNREFUSED 127.0.0.1:80
      at Log.error (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpConnector.<anonymous> (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:382:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

Elasticsearch WARNING: 2018-06-27T12:47:49Z
  Unable to revive connection: http://localhost/

Elasticsearch WARNING: 2018-06-27T12:47:49Z
  No living connections

assert.js:667
    throw newErr;
    ^

AssertionError [ERR_ASSERTION]: ifError got unwanted exception: No Living connections
    at /Users/lgertel/nomikos/node_modules/fastify/fastify.js:316:23
    at Object._encapsulateThreeParam (/Users/lgertel/nomikos/node_modules/avvio/boot.js:357:7)
    at Boot.callWithCbOrNextTick (/Users/lgertel/nomikos/node_modules/avvio/boot.js:308:5)
    at release (/Users/lgertel/nomikos/node_modules/fastq/queue.js:127:16)
    at Object.resume (/Users/lgertel/nomikos/node_modules/fastq/queue.js:61:7)
    at Boot.Plugin.loadPlugin.call (/Users/lgertel/nomikos/node_modules/avvio/boot.js:150:20)
    at toLoad.finish (/Users/lgertel/nomikos/node_modules/avvio/plugin.js:128:7)
    at done (/Users/lgertel/nomikos/node_modules/avvio/plugin.js:86:5)
    at check (/Users/lgertel/nomikos/node_modules/avvio/plugin.js:97:7)
    at sendReqWithConnection (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:225:15)
    at next (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nomikos@1.0.0 dev: `fastify start -l info app.js -P --inspect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nomikos@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lgertel/.npm/_logs/2018-06-27T12_47_49_599Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

Can anybody help me?
Thanks!

**Comment by lgertel** [comment]
Here with trace:
```
[nodemon] restarting due to changes...
[nodemon] starting `npm run dev`

> nomikos@1.0.0 dev /Users/lgertel/nomikos
> fastify start -l info app.js -P --inspect

Elasticsearch INFO: 2018-06-27T13:15:01Z
  Adding connection to http://0.0.0.0/

Elasticsearch DEBUG: 2018-06-27T13:15:01Z
  starting request {
    "method": "HEAD",
    "requestTimeout": 3000,
    "castExists": true,
    "path": "/",
    "query": {}
  }


Elasticsearch TRACE: 2018-06-27T13:15:01Z
  -> HEAD http://0.0.0.0:80/

  <- 0


Elasticsearch ERROR: 2018-06-27T13:15:01Z
  Error: Request error, retrying
  HEAD http://0.0.0.0/ => connect ECONNREFUSED 0.0.0.0:80
      at Log.error (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpConnector.<anonymous> (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:382:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

Elasticsearch TRACE: 2018-06-27T13:15:01Z
  -> HEAD http://0.0.0.0:80/

  <- 0


Elasticsearch WARNING: 2018-06-27T13:15:01Z
  Unable to revive connection: http://0.0.0.0/

Elasticsearch WARNING: 2018-06-27T13:15:01Z
  No living connections

assert.js:667
    throw newErr;
    ^

AssertionError [ERR_ASSERTION]: ifError got unwanted exception: No Living connections
    at /Users/lgertel/nomikos/node_modules/fastify/fastify.js:316:23
    at Object._encapsulateThreeParam (/Users/lgertel/nomikos/node_modules/avvio/boot.js:357:7)
    at Boot.callWithCbOrNextTick (/Users/lgertel/nomikos/node_modules/avvio/boot.js:308:5)
    at release (/Users/lgertel/nomikos/node_modules/fastq/queue.js:127:16)
    at Object.resume (/Users/lgertel/nomikos/node_modules/fastq/queue.js:61:7)
    at Boot.Plugin.loadPlugin.call (/Users/lgertel/nomikos/node_modules/avvio/boot.js:150:20)
    at toLoad.finish (/Users/lgertel/nomikos/node_modules/avvio/plugin.js:128:7)
    at done (/Users/lgertel/nomikos/node_modules/avvio/plugin.js:86:5)
    at check (/Users/lgertel/nomikos/node_modules/avvio/plugin.js:97:7)
    at sendReqWithConnection (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:225:15)
    at next (/Users/lgertel/nomikos/node_modules/fastify-elasticsearch/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nomikos@1.0.0 dev: `fastify start -l info app.js -P --inspect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nomikos@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lgertel/.npm/_logs/2018-06-27T13_15_01_687Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by delvedor** [comment]
Are you working inside docker?

**Comment by allevo** [comment]
Hi! 
Sorry for the delay.
I'm supposing the README is wrong: in the test the `host` key contains the port too.

Could you try to use `host: 'localhost:9200'` ?

**Comment by lgertel** [comment]
Yeah!!!! Great! Fixed yesterday, was about to post it here!
Thanks guys.

**Comment by allevo** [comment]
Would you mind sending a PR to fix the README?

Il gio 28 giu 2018, 13:10 Lucas Gertel <notifications@github.com> ha
scritto:

**Comment by allevo** [comment]
You can just fork and submit a PR

**Comment by delvedor** [comment]
Actually the port value is allowed.
IMHO the issue is probably related to the environment.
